#Global configuration
spring:

  application:
    name: EMarketV2
    #H2 Configuration
    h2.console.enabled: true
  mvc:
    view:
      prefix: /templates/
      suffix:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emarket
    username: root
    password: macron
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /emarket

#Log level configuration
logging:
  level:
    error: DEBUG


